### ISSUE TITLE
Thread safe?

### ISSUE THREAD

**Issue by genius257** [wy3/aup#3]
If possible could your implementation support thread safe code?

**Comment by nomi-san** [comment]
Hi,

It does not matter!
Sorry for my late.

**Comment by genius257** [comment]
Does not matter how?
Would your implementation not allow DLL callback functions?
Or is this thread safe code already a feature of your interpreter?

**Comment by nomi-san** [comment]
Sorry, I mean.. **thread safe** will be implemented in **the future**, not now.
**DLL callback functions** (named in AutoIt3) that I'll try to implement by using [clofn](https://github.com/yulon/clofn).
